# ============================================================================
# 37_gate_d2_modal_auc.R — Gate diagnostic D2: modal-by-modal AUC
# Paper 3 v14 / Path γ++ gate
#
# Purpose: confirm institutional asymmetry by computing AUC against CADE
# cobidders, separately for items conducted under convite (Lei 8.666 Art. 22,
# minimum-bidder rule) and pregão (Lei 10.520, no minimum-bidder rule).
#
# Hypothesis: if loser-side concentration is generated by the convite
# minimum-bidder rule, then firm-level FL features (FL14, log tenders_count)
# should be MORE informative within the convite-exposed subpool than within
# the pregão-only subpool. The relevant statistic is the AUC differential.
#
# We compute AUC using as ground truth the CADE-cobidder set (193 firms),
# but restricting the always-loser pool to firms whose tender footprint is
# concentrated in convite vs pregão.
#
# Pass criterion (Round 3 gate): AUC_convite > AUC_pregao with confidence
# intervals not overlapping at 95%, OR with DeLong p < 0.10. Otherwise AMBIG.
#
# Output: output/gate_d2/d2_modal_auc_results.csv
# ============================================================================

cat("=== 37_gate_d2_modal_auc.R: Diagnostic D2 (modal-by-modal AUC) ===\n")

if (!exists(".script_dir")) .script_dir <- dirname(sys.frame(1)$ofile %||% ".")
suppressPackageStartupMessages({
  library(arrow); library(data.table); library(pROC)
})

BASE <- normalizePath(file.path(.script_dir, ".."), mustWork = FALSE)
OUT  <- file.path(BASE, "output", "gate_d2")
dir.create(OUT, recursive = TRUE, showWarnings = FALSE)

# ---- Load firm-level FL features + cobidder labels -----------------------
fp <- as.data.table(read_parquet(file.path(BASE, "data/processed/FREQ_PARTICIP_rebuilt.parquet")))
fp[, firm_code := as.character(`códigofornecedor`)]
THRESH <- 14L
al <- fp[always_loser == 1L, .(firm_code, tenders_count)]
al[, fl14   := as.integer(tenders_count > THRESH)]
al[, log_tc := log1p(tenders_count)]

cobid <- fread(file.path(BASE, "data/processed/cade_fl_cobidders.csv"))
cobid[, firm_code := sprintf("%014.0f", as.numeric(`códigofornecedor`))]
cobid_codes <- unique(cobid$firm_code)
al[, is_cade := as.integer(firm_code %in% cobid_codes)]

# ---- Compute per-firm modal exposure: share of participations under convite
ftm <- as.data.table(read_parquet(file.path(BASE, "data/processed/firm_tender_map.parquet")))
ftm[, firm_code := as.character(`códigofornecedor`)]

# We need each item's modality. Use bid_level_full_v14 to get
# (numerodaoc, item) -> modality.
suppressPackageStartupMessages({library(duckdb); library(DBI)})
con <- dbConnect(duckdb()); dbExecute(con, "PRAGMA threads=12")
dbExecute(con, "PRAGMA memory_limit='14GB'")
dbExecute(con, "PRAGMA temp_directory='/tmp/duckdb_spill'")
bid_path <- file.path(BASE, "data/processed/bid_level_full_v14.parquet")

cat("\n  Computing item-level modality from bid-level v14 ...\n")
mod_per_item <- as.data.table(dbGetQuery(con, sprintf("
  SELECT
    CAST(\"Numero da OC\" AS VARCHAR) AS numerodaoc,
    CAST(\"Código Item\"  AS VARCHAR) AS codigoitem,
    CASE
      WHEN UPPER(ANY_VALUE(\"Descrição Procedimento Compra\")) = 'CONVITE' THEN 1
      WHEN UPPER(ANY_VALUE(\"Descrição Procedimento Compra\")) IN
        ('PREGÃO ELETRÔNICO','PREGAO ELETRONICO','PREGÃO','PREGAO') THEN 3
      ELSE NULL
    END AS modality
  FROM read_parquet('%s', union_by_name=true)
  GROUP BY numerodaoc, codigoitem
", bid_path)))
dbDisconnect(con, shutdown = TRUE)

cat(sprintf("  Items with modality assigned: %s (convite=%s, pregão=%s)\n",
            format(nrow(mod_per_item), big.mark = ","),
            format(sum(mod_per_item$modality == 1, na.rm = TRUE), big.mark=","),
            format(sum(mod_per_item$modality == 3, na.rm = TRUE), big.mark=",")))

# ---- Per-firm: count of participations under convite vs pregão ----------
ftm[, codigoitem := as.character(`códigoitem`)]
mod_per_item[, codigoitem := as.character(codigoitem)]
ftm_mod <- merge(ftm[, .(firm_code, numerodaoc, codigoitem, won)],
                  mod_per_item, by = c("numerodaoc","codigoitem"), all.x = TRUE)
firm_mod <- ftm_mod[!is.na(modality), .(
  n_convite = sum(modality == 1),
  n_pregao  = sum(modality == 3)
), by = firm_code]
firm_mod[, share_convite := n_convite / pmax(1L, n_convite + n_pregao)]

al <- merge(al, firm_mod, by = "firm_code", all.x = TRUE)
al[is.na(n_convite),    n_convite := 0L]
al[is.na(n_pregao),     n_pregao  := 0L]
al[is.na(share_convite), share_convite := 0]

cat(sprintf("\n  Always-losers with modal assignment: %s\n",
            format(sum(al$n_convite + al$n_pregao > 0), big.mark = ",")))

# ---- Stratify the always-loser pool by primary modal exposure ----------
# convite-primary firms = share_convite >= 0.5 AND ≥ 1 convite participation
# pregão-primary firms  = share_convite < 0.5  AND ≥ 1 pregão participation
al[, modal_pool := fcase(
  share_convite >= 0.5 & n_convite >= 1, "convite_primary",
  share_convite <  0.5 & n_pregao  >= 1, "pregao_primary",
  default = "ambiguous"
)]
cat("\n  Modal-pool split among always-losers:\n")
print(al[, .(N = .N, n_cade = sum(is_cade)), by = modal_pool])

# ---- Compute AUCs per modal pool ----------------------------------------
run_auc <- function(sub, score, label) {
  if (length(unique(sub[[score]])) < 2 || sum(sub$is_cade) < 5) {
    return(NULL)
  }
  r <- pROC::roc(sub$is_cade, sub[[score]], quiet = TRUE)
  list(label = label, score = score,
       auc = as.numeric(pROC::auc(r)),
       ci_lo = as.numeric(pROC::ci(r)[1]),
       ci_hi = as.numeric(pROC::ci(r)[3]),
       n_pos = sum(sub$is_cade),
       n_total = nrow(sub),
       roc = r)
}

results <- list(); rocs <- list()
for (pool in c("convite_primary","pregao_primary","ambiguous","ALL")) {
  sub <- if (pool == "ALL") al else al[modal_pool == pool]
  for (sc in c("fl14","log_tc","tenders_count")) {
    r <- run_auc(sub, sc, paste0(pool,"|",sc))
    if (!is.null(r)) {
      results[[length(results)+1]] <- data.table(
        pool = pool, score = sc,
        auc = r$auc, ci_lo = r$ci_lo, ci_hi = r$ci_hi,
        n_pos = r$n_pos, n_total = r$n_total)
      rocs[[paste0(pool,"|",sc)]] <- r$roc
      cat(sprintf("    [%-15s | %-13s] AUC = %.4f [%.4f, %.4f]  N+ = %d/%d\n",
                  pool, sc, r$auc, r$ci_lo, r$ci_hi, r$n_pos, r$n_total))
    }
  }
}
res_dt <- rbindlist(results, fill = TRUE)
fwrite(res_dt, file.path(OUT, "d2_modal_auc.csv"))

# ---- Pairwise DeLong: convite_primary vs pregao_primary, per score -----
cat("\n  --- DeLong tests: convite_primary vs pregao_primary ---\n")
delong_dt <- data.table()
for (sc in c("fl14","log_tc","tenders_count")) {
  k1 <- paste0("convite_primary|",sc); k2 <- paste0("pregao_primary|",sc)
  if (!is.null(rocs[[k1]]) && !is.null(rocs[[k2]])) {
    # roc.test requires same outcome, but the outcome differs (different
    # firm subsets). Use bootstrap test for AUC difference instead.
    set.seed(20260430)
    nboot <- 500
    bs <- numeric(nboot)
    sub_c <- al[modal_pool == "convite_primary"]
    sub_p <- al[modal_pool == "pregao_primary"]
    if (sum(sub_c$is_cade) >= 5 && sum(sub_p$is_cade) >= 5 &&
        length(unique(sub_c[[sc]])) >= 2 && length(unique(sub_p[[sc]])) >= 2) {
      for (b in 1:nboot) {
        ic <- sample.int(nrow(sub_c), replace = TRUE)
        ip <- sample.int(nrow(sub_p), replace = TRUE)
        if (length(unique(sub_c[[sc]][ic])) < 2 ||
            length(unique(sub_p[[sc]][ip])) < 2 ||
            sum(sub_c$is_cade[ic]) < 2 ||
            sum(sub_p$is_cade[ip]) < 2) {
          bs[b] <- NA_real_
          next
        }
        a_c <- as.numeric(pROC::auc(pROC::roc(sub_c$is_cade[ic],
                                              sub_c[[sc]][ic], quiet = TRUE)))
        a_p <- as.numeric(pROC::auc(pROC::roc(sub_p$is_cade[ip],
                                              sub_p[[sc]][ip], quiet = TRUE)))
        bs[b] <- a_c - a_p
      }
      bs <- bs[!is.na(bs)]
      diff_obs <- res_dt[pool=="convite_primary" & score==sc, auc] -
                  res_dt[pool=="pregao_primary"  & score==sc, auc]
      pval_emp <- 2 * min(mean(bs <= 0), mean(bs >= 0))
      cat(sprintf("    [%s] AUC_conv − AUC_preg = %+.4f  bootstrap p = %.4g  (95%% CI [%.4f, %.4f])\n",
                  sc, diff_obs, pval_emp,
                  quantile(bs, 0.025), quantile(bs, 0.975)))
      delong_dt <- rbind(delong_dt, data.table(
        score = sc, diff_auc = diff_obs, pval_boot = pval_emp,
        ci_lo = quantile(bs, 0.025), ci_hi = quantile(bs, 0.975)))
    }
  }
}
fwrite(delong_dt, file.path(OUT, "d2_modal_delong.csv"))

# ---- Verdict ----------------------------------------------------------
cat("\n  ===== Gate D2 verdict =====\n")
log_tc_diff <- delong_dt[score == "log_tc", diff_auc]
log_tc_p    <- delong_dt[score == "log_tc", pval_boot]
fl14_diff   <- delong_dt[score == "fl14",   diff_auc]
verdict <- (
  if (length(log_tc_diff) > 0 && log_tc_diff > 0 && log_tc_p < 0.10) "PASS"
  else if (length(log_tc_diff) > 0 && log_tc_diff > 0 && log_tc_p < 0.20) "WEAK_PASS"
  else "FAIL"
)
cat(sprintf("    AUC_convite − AUC_pregao (log_tc) = %+.4f  p = %.4g\n",
            ifelse(length(log_tc_diff) > 0, log_tc_diff, NA),
            ifelse(length(log_tc_p) > 0, log_tc_p, NA)))
cat(sprintf("    Diagnostic D2 verdict: %s\n", verdict))

cat("\n  Done.\n")
