name: paper18
channels:
  - conda-forge
  - pyg
  - pytorch
dependencies:
  - python=3.11
  - pip
  - duckdb
  - polars
  - pyarrow
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - networkx
  - geopandas
  - shapely
  - fiona
  - rasterio
  - pyproj
  - tqdm
  - psutil
  - pytorch
  - pytorch-cluster
  - pytorch-scatter
  - pytorch-sparse
  - pyg
  - gensim
  - jupyterlab
  - r-base=4.4
  - r-data.table
  - r-fixest
  - r-did
  - r-kableextra
  - r-sf
  - r-arrow
  - r-duckdb
  - pip:
      - node2vec
      - python-dotenv
      - pyreaddbc
      - dbfread
