from __future__ import annotations

from pathlib import Path

import duckdb

from revision_utils import (
    FIG,
    INTER,
    LOG,
    PROC,
    ROOT,
    TAB,
    begin_log,
    end_log,
    ensure_dirs,
    logger_for,
    parse_args,
    require_force,
    write_text,
)


SCRIPT = "49_audit_project_state"
OUT = ROOT / "notes" / "PROJECT_STATE_AUDIT.md"


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def file_rows(con: duckdb.DuckDBPyConnection, path: Path) -> str:
    try:
        query = f"select count(*) from read_parquet('{path}')"
        return f"{con.sql(query).fetchone()[0]:,}"
    except Exception as exc:
        return f"unreadable ({exc})"


def main() -> None:
    args = parse_args("Audit repository state before AEJ-style revision edits.")
    ensure_dirs()
    log = logger_for(SCRIPT)
    t0 = begin_log(log, SCRIPT)
    if not require_force([OUT], args.force, log):
        return

    con = duckdb.connect()
    con.execute("PRAGMA memory_limit='8GB'")

    numbered = sorted(
        p for p in (ROOT / "03_analysis").iterdir()
        if p.is_file() and p.name[0].isdigit() and p.suffix in {".py", ".R", ".sh"}
    )
    d_scripts = sorted((ROOT / "03_analysis").glob("D*.*"))
    tables = sorted(TAB.glob("*.tex"))
    figures = sorted(p for p in FIG.iterdir() if p.suffix.lower() in {".pdf", ".png", ".svg"})
    data_files = sorted(INTER.glob("*.parquet"))
    processed = sorted(PROC.glob("*")) if PROC.exists() else []

    main_tex = ROOT / "01_manuscript" / "main.tex"
    readme = ROOT / "README.md"
    build_cmd = "cd 01_manuscript && pdflatex main && bibtex main && pdflatex main && pdflatex main"
    if readme.exists():
        text = readme.read_text(encoding="utf-8")
        if "pdflatex main && bibtex main && pdflatex main && pdflatex main" not in text:
            build_cmd = "not documented in README.md"

    inputs = []
    if main_tex.exists():
        for i, line in enumerate(main_tex.read_text(encoding="utf-8").splitlines(), 1):
            if "\\input{" in line or "\\bibliography{" in line:
                inputs.append(f"- `{rel(main_tex)}:{i}` `{line.strip()}`")

    used_tables = []
    used_figures = []
    for tex in sorted((ROOT / "01_manuscript").glob("*.tex")):
        for i, line in enumerate(tex.read_text(encoding="utf-8").splitlines(), 1):
            if "tables/" in line:
                used_tables.append(f"- `{rel(tex)}:{i}` `{line.strip()}`")
            if "\\includegraphics" in line:
                used_figures.append(f"- `{rel(tex)}:{i}` `{line.strip()}`")

    data_inventory = []
    for path in data_files:
        if path.name.startswith(("staggered", "hospital_", "exposure", "travel", "psych", "icsap", "bipartite", "osrm", "pop_", "pib_", "closures")):
            data_inventory.append(f"- `{rel(path)}`: {file_rows(con, path)} rows")

    content = "\n".join([
        "# Project State Audit",
        "",
        "Generated by `03_analysis/49_audit_project_state.py`.",
        "",
        "## Manuscript",
        f"- Entry point: `{rel(main_tex)}`",
        f"- PDF build command: `{build_cmd}`",
        "",
        "### Main Inputs",
        *inputs,
        "",
        "### Tables Referenced By Manuscript",
        *(used_tables or ["- none found"]),
        "",
        "### Figures Referenced By Manuscript",
        *(used_figures or ["- none found"]),
        "",
        "## Existing Numbered Scripts",
        *[f"- `{rel(p)}`" for p in numbered],
        "",
        "## Existing D-Scripts",
        *[f"- `{rel(p)}`" for p in d_scripts],
        "",
        "## Key Intermediate Data Files",
        *data_inventory,
        "",
        "## Existing Manuscript Tables",
        *[f"- `{rel(p)}`" for p in tables],
        "",
        "## Existing Figures",
        *[f"- `{rel(p)}`" for p in figures],
        "",
        "## Existing Processed Outputs",
        *([f"- `{rel(p)}`" for p in processed] or ["- none before this revision block"]),
        "",
    ])
    write_text(OUT, content)
    log.info("wrote %s", rel(OUT))
    end_log(log, t0)


if __name__ == "__main__":
    main()
