#!/usr/bin/env Rscript
# D7_inference.R
#
# Robustness of the suicide null to the small number of effective clusters
# (identification rests on ~48 psychiatric closures, not the ~5,500 municipality
# clusters). Two design-based / conservative inference checks on the headline
# population-weighted suicide ATT (pnash48_ext):
#   (1) re-cluster SEs at the Federation Unit (UF) level;
#   (2) randomization inference: permute the municipality->cohort treatment
#       assignment B times, re-estimate the SunAb simple ATT, and compare the
#       observed estimate to the placebo distribution.
#
# Writes values_inference.tex (macros) + logs the placebo distribution.

suppressPackageStartupMessages({ library(arrow); library(data.table); library(fixest) })

trailing <- commandArgs(trailingOnly = TRUE)
arg_value <- function(flag, default) {
  hit <- grep(paste0("^", flag, "="), trailing, value = TRUE)
  if (length(hit)) sub(paste0("^", flag, "="), "", hit[[1]]) else default
}
force <- "--force" %in% trailing
ROOT  <- normalizePath(file.path(dirname(sub("--file=", "",
          commandArgs(FALSE)[grepl("--file=", commandArgs(FALSE))])), ".."))
INTER <- file.path(ROOT, "02_data", "intermediate")
OUT   <- file.path(ROOT, "01_manuscript", "values_inference.tex")
LOG   <- file.path(ROOT, "04_logs")
B     <- as.integer(arg_value("--B", "100"))
CACHE <- file.path(LOG, sprintf("D7_inference_B%d.rds", B))

d <- as.data.table(read_parquet(file.path(INTER, "staggered_panel_pnash48_ext.parquet")))
d <- d[is.finite(suicide_per100k) & is.finite(pop)]
d[, gn := ifelse(is.na(g_emb) | g_emb == 0, 10000L, as.integer(g_emb))]

att_of <- function(dat) {
  m <- feols(suicide_per100k ~ sunab(gn, year) | muni_id + year,
             data = dat, cluster = "muni_id", weights = ~pop)
  as.numeric(coef(summary(m, agg = "att"))[1])
}

# ---- observed, muni- and UF-clustered ----
m_base <- feols(suicide_per100k ~ sunab(gn, year) | muni_id + year, d, cluster = "muni_id", weights = ~pop)
m_uf   <- feols(suicide_per100k ~ sunab(gn, year) | muni_id + year, d, cluster = ~uf, weights = ~pop)
att     <- as.numeric(coef(summary(m_base, agg = "att"))[1])
se_muni <- as.numeric(se(summary(m_base, agg = "att"))[1])
se_uf   <- as.numeric(se(summary(m_uf,   agg = "att"))[1])
n_uf    <- d[, uniqueN(uf)]
cat(sprintf("observed ATT=%+.3f | SE muni=%.3f (CI [%+.2f,%+.2f]) | SE UF=%.3f over %d UFs (CI [%+.2f,%+.2f])\n",
            att, se_muni, att-1.96*se_muni, att+1.96*se_muni, se_uf, n_uf, att-1.96*se_uf, att+1.96*se_uf))

# ---- randomization inference: shuffle muni -> g_emb mapping ----
if (file.exists(CACHE) && !force) {
  cached <- readRDS(CACHE)
  placebo <- cached$placebo
  cat(sprintf("reused cached RI distribution: %s (%d valid placebos)\n",
              CACHE, sum(is.finite(placebo))))
} else {
  muni_g <- unique(d[, .(muni_id, g_emb)])           # one cohort label per municipality
  set.seed(42)
  placebo <- numeric(B)
  base <- d[, !"g_emb"]
  setkey(base, muni_id)
  t0 <- Sys.time()
  for (b in seq_len(B)) {
    perm <- copy(muni_g)
    perm[, g_emb := sample(g_emb)]   # permute treatment timing across munis
    setkey(perm, muni_id)
    dd <- perm[base]
    dd[, gn := ifelse(is.na(g_emb) | g_emb == 0, 10000L, as.integer(g_emb))]
    placebo[b] <- tryCatch(att_of(dd), error = function(e) NA_real_)
    if (b %% 100 == 0) cat(sprintf("  RI %d/%d  (%.0fs)\n", b, B, as.numeric(Sys.time()-t0, units="secs")))
  }
  saveRDS(list(att=att, se_muni=se_muni, se_uf=se_uf, placebo=placebo, B=B),
          CACHE)
}
placebo <- placebo[is.finite(placebo)]
ri_p <- mean(abs(placebo) >= abs(att))             # two-sided RI p-value for H0: ATT=0
ri_lo <- quantile(placebo, 0.025); ri_hi <- quantile(placebo, 0.975)
cat(sprintf("\nRI: %d valid placebos | p(|placebo|>=|obs|)=%.3f | placebo 95%% [%+.2f,%+.2f] | placebo SD=%.3f\n",
            length(placebo), ri_p, ri_lo, ri_hi, sd(placebo)))

saveRDS(list(att=att, se_muni=se_muni, se_uf=se_uf, placebo=placebo, ri_p=ri_p, B=B),
        file.path(LOG, "D7_inference.rds"))

# ---- macros ----
sgn <- function(x) sprintf("%+.2f", x)
writeLines(c(
  "% Auto-generated by 03_analysis/D7_inference.R — do not hand-edit.",
  sprintf("\\newcommand{\\valSuicSeUF}{%.2f}%% src: D7: suicide WLS SE clustered at UF (%d clusters)", se_uf, n_uf),
  sprintf("\\newcommand{\\valSuicUFLo}{%s}%% src: D7: UF-clustered 95%% CI lower", sgn(att-1.96*se_uf)),
  sprintf("\\newcommand{\\valSuicUFHi}{%s}%% src: D7: UF-clustered 95%% CI upper", sgn(att+1.96*se_uf)),
  sprintf("\\newcommand{\\valSuicRIp}{%.2f}%% src: D7: randomization-inference two-sided p, B=%d", ri_p, B),
  sprintf("\\newcommand{\\valSuicRILo}{%s}%% src: D7: RI placebo 2.5 pct", sgn(as.numeric(ri_lo))),
  sprintf("\\newcommand{\\valSuicRIHi}{%s}%% src: D7: RI placebo 97.5 pct", sgn(as.numeric(ri_hi))),
  sprintf("\\newcommand{\\valNUFclusters}{%d}%% src: D7: number of UF clusters", n_uf)
), OUT)
cat("wrote", OUT, "\n")
