# Paths, DuckDB config e helpers comuns para os scripts v6-jpube.
# Adaptado de utils_v3.R com (i) raiz redirecionada para v6-jpube,
# (ii) helper write_macro() para alimentar output/values.tex e
# (iii) reset_macros() chamado pelo orquestrador 00_master.R.

suppressPackageStartupMessages({
  library(data.table)
  library(duckdb)
  library(DBI)
  library(arrow)
})

v6_root   <- "/home/darciogm1/projetos/bitter-pills/paper2-me-epp/v6-jpube"
data_root <- "/home/darciogm1/projetos/bitter-pills/paper2-me-epp/data"
p3_data   <- "/home/darciogm1/projetos/bitter-pills/paper3-frequent-losers/data/processed"

# RNG seed registry (defines MASTER_SEED, seed_for_script, seed_for_iter).
# Every numbered script that draws random numbers must call
# set.seed(seed_for_script(NN)) at the top.
source(file.path(v6_root, "scripts", "seeds.R"))

path_v6  <- function(...) file.path(v6_root, ...)
path_raw  <- function(...) file.path(data_root, "raw", ...)
path_proc <- function(...) file.path(data_root, "processed", ...)

# Backward-compatibility shim: v6 scripts ainda podem citar path_v3().
# Aponta para v6_root para evitar cross-contamination com v3-structural.
path_v3 <- path_v6

dir.create(path_v6("data/processed"), showWarnings = FALSE, recursive = TRUE)
dir.create(path_v6("logs"),           showWarnings = FALSE, recursive = TRUE)
dir.create(path_v6("output/tables"),  showWarnings = FALSE, recursive = TRUE)
dir.create(path_v6("output/figures"), showWarnings = FALSE, recursive = TRUE)

con_duck <- function() {
  con <- dbConnect(duckdb::duckdb())
  dbExecute(con, "PRAGMA threads=12")
  dbExecute(con, "PRAGMA memory_limit='14GB'")
  dbExecute(con, "PRAGMA temp_directory='/tmp/duckdb_spill_v6'")
  con
}

rss_gb <- function() {
  tryCatch({
    info <- system(paste0("ps -p ", Sys.getpid(), " -o rss="), intern = TRUE)
    round(as.numeric(info) / 1024^2, 2)
  }, error = function(e) NA_real_)
}

log_step <- function(tag, msg, log_con = NULL) {
  line <- sprintf("[%s] %s  RSS=%.2fGb  %s",
                  format(Sys.time(), "%H:%M:%S"), tag, rss_gb(), msg)
  message(line)
  if (!is.null(log_con)) writeLines(line, log_con)
}

# ---------------------------------------------------------------------------
# Macro registry: every numerical claim that aparece no manuscrito vem daqui.
# values.tex é regravado a cada rodada do pipeline e \input{} no preamble do
# paper_v6.tex. Não editar à mão.
# ---------------------------------------------------------------------------

values_path <- function() path_v6("output/values.tex")

reset_macros <- function() {
  dir.create(dirname(values_path()), showWarnings = FALSE, recursive = TRUE)
  writeLines(c(
    "% AUTO-GENERATED by v6-jpube pipeline. DO NOT EDIT BY HAND.",
    paste0("% Generated: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
    "% Source scripts: v6-jpube/scripts/[0-9]*.R",
    ""
  ), values_path())
}

# Idempotent within a single pipeline run: if a macro is rewritten by a later
# script, the latest definition wins (LaTeX uses the last \newcommand or
# \renewcommand). We always emit \providecommand + \renewcommand to be safe.
write_macro <- function(name, value, fmt = NULL, comment = NULL) {
  if (!grepl("^[A-Za-z]+$", name)) {
    stop("Macro name must be letters-only (LaTeX restriction): ", name)
  }
  if (!is.null(fmt) && is.numeric(value)) {
    txt <- sprintf(fmt, value)
  } else if (is.numeric(value)) {
    txt <- formatC(value, digits = 4, format = "g")
  } else {
    txt <- as.character(value)
  }
  cmnt <- if (!is.null(comment)) paste0(" % ", comment) else ""
  block <- c(
    sprintf("\\providecommand{\\%s}{}", name),
    sprintf("\\renewcommand{\\%s}{%s}%s", name, txt, cmnt)
  )
  cat(paste(block, collapse = "\n"), "\n",
      file = values_path(), append = TRUE, sep = "")
  invisible(block)
}

# Convenience wrappers for common formatting needs.
write_macro_pct <- function(name, value, digits = 1, comment = NULL) {
  write_macro(name, value, fmt = paste0("%.", digits, "f"), comment = comment)
}
write_macro_money <- function(name, value, digits = 0, scale = 1, comment = NULL) {
  write_macro(name, value / scale, fmt = paste0("%.", digits, "f"), comment = comment)
}
write_macro_int <- function(name, value, comment = NULL) {
  write_macro(name, value, fmt = "%d", comment = comment)
}
write_macro_dec <- function(name, value, digits = 3, comment = NULL) {
  write_macro(name, value, fmt = paste0("%.", digits, "f"), comment = comment)
}

cadmat_pharma_narrow <- c(6531L, 6532L, 6536L, 6581L)
cadmat_pharma_broad  <- c(6509L, 6528L, 6531L, 6532L, 6533L, 6534L, 6536L,
                          6541L, 6542L, 6573L, 6574L, 6575L, 6576L, 6577L,
                          6578L, 6579L, 6581L, 6582L, 6586L)

cutoff_m <- 698L
win_18m  <- c(680L, 715L)
win_12m  <- c(686L, 709L)
win_06m  <- c(692L, 703L)
